## 1. Pandas
This tutorial is assuming that you have some basic programming skills. If you are more familiar with R than with Python, don't worry, it's not that different. First, we will have a look at the pandas package, which introduces the data frame (similar to R) as a fundamental data structure.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("iris.csv")

df

/home/AD.IGD.FRAUNHOFER.DE/sluedtke/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

,Unnamed: 0,SepalLength,SepalWidth,PetalLength,PetalWidth,Name
0,0,5.1,3.5,1.4,0.2,Iris-setosa
1,1,4.9,3.0,1.4,0.2,Iris-setosa
2,2,4.7,3.2,1.3,0.2,Iris-setosa
3,3,4.6,3.1,1.5,0.2,Iris-setosa
4,4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,Iris-virginica
146,146,6.3,2.5,5.0,1.9,Iris-virginica
147,147,6.5,3.0,5.2,2.0,Iris-virginica
148,148,6.2,3.4,5.4,2.3,Iris-virginica
149,149,5.9,3.0,5.1,1.8,Iris-virginica

### Selecting rows / columns
Using pandas, we can easily select rows or columns in a data frame. One option is to select via name of the column:

In [ ]:
accx = df.loc[:,"SepalLength"]
accx

Here, `:` means "choose all rows". When only a single column is selected, the result is of type `Series`, otherwise it is a data frame again. We can also access columns via their index:

In [ ]:
acc = df.iloc[:,1:4]
acc

We can access rows in the same way. The following expression gives us a data frame consisting of the first five rows:

In [ ]:
df.iloc[0:5,:]

These can both be combined like this:

In [ ]:
df.loc[0:5,["SepalLength", "SepalWidth"]]

Another option is to access rows or columns via boolean expressions. For example, the following line returns a data frame that only contains rows whose `SepalLength` is smaller than 5:

In [ ]:
df.loc[df.SepalLength < 5,:]

### Adding new values
Writing new values in a data frame is also easy. The following expression replaces all values of the column `SepalLength` that are smaller than 5 to the value 0.

In [ ]:
df.loc[df.SepalLength < 0,"SepalLength"] = 0
df

## 2. Decision Trees in Python 
The following example trains a decision tree on the Iris data, using 2/3 as training data and 1/3 as test data.

In [2]:
import sklearn

X = df.iloc[:,1:5]
y = df.iloc[:,5]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33)

In [4]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [5]:
pred = clf.predict(X_test)
print(np.mean(pred==y_test))

0.92

## 3. Task: Train your own model
Next, you can try to train a model yourself: we want you to use the Titanic passenger data (name, age, price of ticket, etc) to try to predict who will survive and who will die.

In [2]:
import pandas as pd

titanic = pd.read_csv("titanic.csv")

/home/AD.IGD.FRAUNHOFER.DE/sluedtke/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Explain the model
Compute SHAP values of the model and plot them as a beeswarm plot.